### ISSUE TITLE
New Token--Shadrock Roberts

### ISSUE THREAD

**Issue by Shadrock** [hotosm/oam-uploader-admin#53]
Name: Shadrock Roberts
Email: shadrock.roberts@gmail.com
Location of imagery: Athens, GA, USA. [Lat/Long approx: 33.93376, -83.37327](http://www.openstreetmap.org/#map=17/33.93365/-83.37341)
Source of imagery: Homemade drone with rigged keychain camera.
Short description of collection: High oblique image created by taking still shots from video and stitching them together. 
Have you received approval for making this imagery available (yes/no)?: Yes

**Comment by smit1678** [comment]
@Shadrock Thanks for contributing! An email was sent with your token.

**Comment by Shadrock** [comment]
Thanks @smit1678, I'm looking forward to adding a few projects, which will probably be the crappiest imagery on here! However, I'm having problems uploading via Flickr and can't find any documentation on that. Are URLs really limited to Dropbox and Drive or should I submit a new issue for this?

**Comment by smit1678** [comment]
@Shadrock Just looked at the error messages. We haven't tested Flickr URLs a lot, but it looks like you need to supply the direct file download (linking to flickr.com url won't work). A URL like https://c2.staticflickr.com/4/3928/33805429012_ed66532eff_o.jpg should work. Another option is that you should be able to upload a local file if you have it downloaded already. 

But I noticed another problem with the image. It's not projected. It needs to have a coordinate reference system assigned in order to correctly be georeferenced. Is this something you can add or is this something that is stripped when you upload to Flickr?
